-- 创建成语表
CREATE TABLE IF NOT EXISTS idioms (
    id SERIAL PRIMARY KEY,
    content VARCHAR(20) NOT NULL UNIQUE,
    pinyin VARCHAR(100) NOT NULL,
    first_char VARCHAR(10) NOT NULL,
    last_char VARCHAR(10) NOT NULL
);

-- 插入50个四字成语，确保可以接龙
INSERT INTO idioms (content, pinyin, first_char, last_char) VALUES 
('一帆风顺', 'yī fān fēng shùn', '一', '顺'),
('顺水人情', 'shùn shuǐ rén qíng', '顺', '情'),
('情同手足', 'qíng tóng shǒu zú', '情', '足'),
('足智多谋', 'zú zhì duō móu', '足', '谋'),
('谋事在人', 'móu shì zài rén', '谋', '人'),
('人才辈出', 'rén cái bèi chū', '人', '出'),
('出人头地', 'chū rén tóu dì', '出', '地'),
('地久天长', 'dì jiǔ tiān cháng', '地', '长'),
('长生不老', 'cháng shēng bù lǎo', '长', '老'),
('老当益壮', 'lǎo dāng yì zhuàng', '老', '壮'),
('壮志凌云', 'zhuàng zhì líng yún', '壮', '云'),
('云开见日', 'yún kāi jiàn rì', '云', '日'),
('日新月异', 'rì xīn yuè yì', '日', '异'),
('异想天开', 'yì xiǎng tiān kāi', '异', '开'),
('开门见山', 'kāi mén jiàn shān', '开', '山'),
('山清水秀', 'shān qīng shuǐ xiù', '山', '秀'),
('秀外慧中', 'xiù wài huì zhōng', '秀', '中'),
('中流砥柱', 'zhōng liú dǐ zhù', '中', '柱'),
('柱石之坚', 'zhù shí zhī jiān', '柱', '坚'),
('坚不可摧', 'jiān bù kě cuī', '坚', '摧'),
('摧枯拉朽', 'cuī kū lā xiǔ', '摧', '朽'),
('朽木难雕', 'xiǔ mù nán diāo', '朽', '雕'),
('雕虫小技', 'diāo chóng xiǎo jì', '雕', '技'),
('技高一筹', 'jì gāo yī chóu', '技', '筹'),
('筹交错', 'gōng chóu jiāo cuò', '觥', '错'),
('错落有致', 'cuò luò yǒu zhì', '错', '致'),
('致远任重', 'zhì yuǎn rèn zhòng', '致', '重'),
('重于泰山', 'zhòng yú tài shān', '重', '山'),
('山高水长', 'shān gāo shuǐ cháng', '山', '长'),
('长驱直入', 'cháng qū zhí rù', '长', '入'),
('入木三分', 'rù mù sān fēn', '入', '分'),
('分秒必争', 'fēn miǎo bì zhēng', '分', '争'),
('争先恐后', 'zhēng xiān kǒng hòu', '争', '后'),
('后继有人', 'hòu jì yǒu rén', '后', '人'),
('人山人海', 'rén shān rén hǎi', '人', '海'),
('海阔天空', 'hǎi kuò tiān kōng', '海', '空'),
('空穴来风', 'kōng xué lái fēng', '空', '风'),
('风调雨顺', 'fēng tiáo yǔ shùn', '风', '顺'),
('顺手牵羊', 'shùn shǒu qiān yáng', '顺', '羊'),
('羊肠小道', 'yáng cháng xiǎo dào', '羊', '道'),
('道听途说', 'dào tīng tú shuō', '道', '说'),
('说三道四', 'shuō sān dào sì', '说', '四'),
('四面楚歌', 'sì miàn chǔ gē', '四', '歌'),
('歌舞升平', 'gē wǔ shēng píng', '歌', '平'),
('平步青云', 'píng bù qīng yún', '平', '云'),
('云淡风轻', 'yún dàn fēng qīng', '云', '轻'),
('轻而易举', 'qīng ér yì jǔ', '轻', '举'),
('举一反三', 'jǔ yī fǎn sān', '举', '三'),
('三生有幸', 'sān shēng yǒu xìng', '三', '幸'),
('幸灾乐祸', 'xìng zāi lè huò', '幸', '祸')
ON CONFLICT (content) DO NOTHING;