-- Create database if not exists
CREATE DATABASE IF NOT EXISTS idiom_db;

\c idiom_db;

-- Create idioms table
CREATE TABLE IF NOT EXISTS idioms (
    id SERIAL PRIMARY KEY,
    idiom VARCHAR(20) NOT NULL UNIQUE,
    first_char VARCHAR(10) NOT NULL,
    last_char VARCHAR(10) NOT NULL,
    pinyin VARCHAR(100)
);

-- Insert common Chinese idioms
INSERT INTO idioms (idiom, first_char, last_char, pinyin) VALUES
('一帆风顺', '一', '顺', 'yī fān fēng shùn'),
('顺水推舟', '顺', '舟', 'shùn shuǐ tuī zhōu'),
('舟车劳顿', '舟', '顿', 'zhōu chē láo dùn'),
('顿开茅塞', '顿', '塞', 'dùn kāi máo sāi'),
('塞翁失马', '塞', '马', 'sài wēng shī mǎ'),
('马到成功', '马', '功', 'mǎ dào chéng gōng'),
('功成名就', '功', '就', 'gōng chéng míng jiù'),
('就事论事', '就', '事', 'jiù shì lùn shì'),
('事倍功半', '事', '半', 'shì bèi gōng bàn'),
('半途而废', '半', '废', 'bàn tú ér fèi'),
('废寝忘食', '废', '食', 'fèi qǐn wàng shí'),
('食不甘味', '食', '味', 'shí bù gān wèi'),
('味同嚼蜡', '味', '蜡', 'wèi tóng jiáo là'),
('蜡炬成灰', '蜡', '灰', 'là jù chéng huī'),
('灰飞烟灭', '灰', '灭', 'huī fēi yān miè'),
('灭绝人性', '灭', '性', 'miè jué rén xìng'),
('性烈如火', '性', '火', 'xìng liè rú huǒ'),
('火树银花', '火', '花', 'huǒ shù yín huā'),
('花好月圆', '花', '圆', 'huā hǎo yuè yuán'),
('圆满结束', '圆', '束', 'yuán mǎn jié shù'),
('束手无策', '束', '策', 'shù shǒu wú cè'),
('策无遗算', '策', '算', 'cè wú yí suàn'),
('算沙抟空', '算', '空', 'suàn shā tuán kōng'),
('空穴来风', '空', '风', 'kōng xué lái fēng'),
('风餐露宿', '风', '宿', 'fēng cān lù sù'),
('宿弊一清', '宿', '清', 'sù bì yī qīng'),
('清风明月', '清', '月', 'qīng fēng míng yuè'),
('月黑风高', '月', '高', 'yuè hēi fēng gāo'),
('高山流水', '高', '水', 'gāo shān liú shuǐ'),
('水到渠成', '水', '成', 'shuǐ dào qú chéng'),
('成千上万', '成', '万', 'chéng qiān shàng wàn'),
('万紫千红', '万', '红', 'wàn zǐ qiān hóng'),
('红装素裹', '红', '裹', 'hóng zhuāng sù guǒ'),
('裹足不前', '裹', '前', 'guǒ zú bù qián'),
('前功尽弃', '前', '弃', 'qián gōng jìn qì'),
('弃暗投明', '弃', '明', 'qì àn tóu míng'),
('明察秋毫', '明', '毫', 'míng chá qiū háo'),
('毫不动摇', '毫', '摇', 'háo bù dòng yáo'),
('摇身一变', '摇', '变', 'yáo shēn yī biàn'),
('变本加厉', '变', '厉', 'biàn běn jiā lì'),
('厉兵秣马', '厉', '马', 'lì bīng mò mǎ'),
('马革裹尸', '马', '尸', 'mǎ gé guǒ shī'),
('尸位素餐', '尸', '餐', 'shī wèi sù cān'),
('餐风饮露', '餐', '露', 'cān fēng yǐn lù'),
('露胆披肝', '露', '肝', 'lù dǎn pī gān'),
('肝脑涂地', '肝', '地', 'gān nǎo tú dì'),
('地久天长', '地', '长', 'dì jiǔ tiān cháng'),
('长驱直入', '长', '入', 'cháng qū zhí rù'),
('入木三分', '入', '分', 'rù mù sān fēn'),
('分秒必争', '分', '争', 'fēn miǎo bì zhēng'),
('争先恐后', '争', '后', 'zhēng xiān kǒng hòu'),
('后继有人', '后', '人', 'hòu jì yǒu rén'),
('人才辈出', '人', '出', 'rén cái bèi chū'),
('出神入化', '出', '化', 'chū shén rù huà'),
('化险为夷', '化', '夷', 'huà xiǎn wéi yí'),
('夷为平地', '夷', '地', 'yí wéi píng dì'),
('地大物博', '地', '博', 'dì dà wù bó'),
('博古通今', '博', '今', 'bó gǔ tōng jīn'),
('今非昔比', '今', '比', 'jīn fēi xī bǐ'),
('比比皆是', '比', '是', 'bǐ bǐ jiē shì'),
('是非曲直', '是', '直', 'shì fēi qū zhí'),
('直截了当', '直', '当', 'zhí jié liǎo dàng'),
('当仁不让', '当', '让', 'dāng rén bù ràng'),
('让枣推梨', '让', '梨', 'ràng zǎo tuī lí'),
('梨花带雨', '梨', '雨', 'lí huā dài yǔ'),
('雨过天晴', '雨', '晴', 'yǔ guò tiān qíng'),
('晴空万里', '晴', '里', 'qíng kōng wàn lǐ'),
('里应外合', '里', '合', 'lǐ yìng wài hé'),
('合情合理', '合', '理', 'hé qíng hé lǐ'),
('理直气壮', '理', '壮', 'lǐ zhí qì zhuàng'),
('壮志凌云', '壮', '云', 'zhuàng zhì líng yún'),
('云蒸霞蔚', '云', '蔚', 'yún zhēng xiá wèi'),
('蔚然成风', '蔚', '风', 'wèi rán chéng fēng'),
('风华正茂', '风', '茂', 'fēng huá zhèng mào'),
('茂林修竹', '茂', '竹', 'mào lín xiū zhú'),
('竹报平安', '竹', '安', 'zhú bào píng ān'),
('安邦定国', '安', '国', 'ān bāng dìng guó'),
('国泰民安', '国', '安', 'guó tài mín ān'),
('安居乐业', '安', '业', 'ān jū lè yè'),
('业精于勤', '业', '勤', 'yè jīng yú qín'),
('勤能补拙', '勤', '拙', 'qín néng bǔ zhuō'),
('拙嘴笨舌', '拙', '舌', 'zhuō zuǐ bèn shé'),
('舌战群儒', '舌', '儒', 'shé zhàn qún rú'),
('儒雅风流', '儒', '流', 'rú yǎ fēng liú'),
('流连忘返', '流', '返', 'liú lián wàng fǎn'),
('返璞归真', '返', '真', 'fǎn pú guī zhēn'),
('真才实学', '真', '学', 'zhēn cái shí xué'),
('学富五车', '学', '车', 'xué fù wǔ chē'),
('车水马龙', '车', '龙', 'chē shuǐ mǎ lóng'),
('龙飞凤舞', '龙', '舞', 'lóng fēi fèng wǔ'),
('舞文弄墨', '舞', '墨', 'wǔ wén nòng mò'),
('墨守成规', '墨', '规', 'mò shǒu chéng guī'),
('规行矩步', '规', '步', 'guī xíng jǔ bù'),
('步步为营', '步', '营', 'bù bù wéi yíng'),
('营私舞弊', '营', '弊', 'yíng sī wǔ bì'),
('弊绝风清', '弊', '清', 'bì jué fēng qīng'),
('清风劲节', '清', '节', 'qīng fēng jìn jié'),
('节衣缩食', '节', '食', 'jié yī suō shí'),
('食古不化', '食', '化', 'shí gǔ bù huà'),
('化干戈为玉帛', '化', '帛', 'huà gān gē wéi yù bó'),
('帛戈交错', '帛', '错', 'bó gē jiāo cuò'),
('错落有致', '错', '致', 'cuò luò yǒu zhì'),
('致远任重', '致', '重', 'zhì yuǎn rèn zhòng'),
('重峦叠嶂', '重', '嶂', 'chóng luán dié zhàng'),
('嶂翳难通', '嶂', '通', 'zhàng yì nán tōng'),
('通情达理', '通', '理', 'tōng qíng dá lǐ'),
('理屈词穷', '理', '穷', 'lǐ qū cí qióng'),
('穷途末路', '穷', '路', 'qióng tú mò lù'),
('路人皆知', '路', '知', 'lù rén jiē zhī'),
('知难而上', '知', '上', 'zhī nán ér shàng'),
('上天入地', '上', '地', 'shàng tiān rù dì'),
('地老天荒', '地', '荒', 'dì lǎo tiān huāng'),
('荒无人烟', '荒', '烟', 'huāng wú rén yān'),
('烟消云散', '烟', '散', 'yān xiāo yún sàn'),
('散兵游勇', '散', '勇', 'sàn bīng yóu yǒng'),
('勇往直前', '勇', '前', 'yǒng wǎng zhí qián'),
('前赴后继', '前', '继', 'qián fù hòu jì'),
('继往开来', '继', '来', 'jì wǎng kāi lái'),
('来者不善', '来', '善', 'lái zhě bù shàn'),
('善始善终', '善', '终', 'shàn shǐ shàn zhōng'),
('终而复始', '终', '始', 'zhōng ér fù shǐ'),
('始终如一', '始', '一', 'shǐ zhōng rú yī')
ON CONFLICT (idiom) DO NOTHING;